spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/loyaltydb

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      atlas:
        enabled: false
  endpoint:
    health:
      show-details: always
  trace:
    http:
      enabled: true

info:
  app:
    name: CustomerLoyalty
    description: Customer Loyalty
    encoding: UTF-8
    version: 1.0.1
    java:
      version: 1.8

jwt:
  secret: javainuse